# Had to add `network_mode: host`, otherwise received
# UnhandledPromiseRejectionWarning:
#  Error: connect ECONNREFUSED 127.0.0.1:4005
# with the addition of `app.post('http://localhost:4005/event', {})`
# to posts and comments services.
version: "2.4"
services:
  client:
    build:
      context: ./client
      target: dev
    ports:
      - 3000:3000
    volumes:
      - client_node_modules:/app/node_modules
      - ./client:/app
    network_mode: host
  comments:
    build:
      context: ./comments
      target: dev
    ports:
      - 4001:4001
    volumes:
      - comments_node_modules:/app/node_modules
      - ./comments:/app
    network_mode: host
  posts:
    build:
      context: ./posts
      target: dev
    ports:
      - 4000:4000
    volumes:
      - posts_node_modules:/app/node_modules
      - ./posts:/app
    network_mode: host
  query:
    build:
      context: ./query
      target: dev
    ports:
      - 4002:4002
    volumes:
      - ./query:/app
      - query_node_modules:/app/node_modules
    network_mode: host
  moderation:
    build:
      context: ./moderation
      target: dev
    ports:
      - 4003:4003
    volumes:
      - moderation_node_modules:/app/node_modules
      - ./moderation:/app
    network_mode: host
  event-bus:
    build:
      context: ./event-bus
      target: dev
    ports:
      - 4005:4005
    volumes:
      - event-bus_node_modules:/app/node_modules
      - ./event-bus:/app
    network_mode: host

volumes:
  client_node_modules:
  comments_node_modules:
  posts_node_modules:
  query_node_modules:
  event-bus_node_modules:
  moderation_node_modules:
